### ISSUE TITLE
Decouple Graphvix

### ISSUE THREAD

**Issue by hl** [zorbash/opus#10]
### Environment

* opus version: 0.5.1
* Elixir / Hex version (mix hex.info): 
    - Hex:    0.18.2
    - Elixir: 1.7.4
    - OTP:    21.1.1

* Operating system: MacOS 10.14.1

### Current behavior

This is both a bug report and feature request. I think it's better to decouple Graphvix from Opus because it doesn't add anything for production. I'm also getting the below error on version 0.5 (version 1.0 is released)

`[error] Graphvix.Graph Graphvix.Graph received unexpected message in handle_info/2: :save_state`

### Expected behavior

No error and decoupling

**Comment by zorbash** [comment]
I'm extracting this to a separate optional package on which you can depend on the environments you intend to run `Opus.Graph` using:

```elixir
# in mix.exs
def deps
  {:opus, "> 0.5"},
  {:opus_graph, "~> 0.1", only: [:dev]}
end
```

**Comment by zorbash** [comment]
`opus_graph` has been published, so you if you depend on the edge version of opus you won't have that issue. Let me know if that works for you.

**Comment by hl** [comment]
Works great, thanks!

**Comment by zorbash** [comment]
@hl btw if you're using the library and you find it useful, consider suggesting it to be included in
https://github.com/h4cc/awesome-elixir 🙏

**Comment by churcho** [comment]
I am getting this error when I run my tests `Graphvix.Graph Graphvix.Graph received unexpected message in handle_info/2: :save_state` and I can see it's referenced in this issue.

What could I be missing?
I am using the latest branch.

**Comment by zorbash** [comment]
@churcho Do you depend on the master branch of this library `08ed635a9936e83ef779524ace9fc63122e14ff8` ?

**Comment by churcho** [comment]
@zorbash not getting this anymore with the new update.
