### ISSUE TITLE
Add a :unless param for stages

### ISSUE THREAD

**Issue by rafaels88** [zorbash/opus#13]
### Proposal

Add the ability to pass a `:unless` parameter for all the stages where it is possible to pass a `:if` one.

The idea is that you don't need to name your functions like `not_*` in order to add a new stage to the pipeline.

### Context

Imagine we can perform a step only if the _user is allowed_.

```elixir
defmodule Pipeline do
  use Opus.Pipeline

  step :do_this, if: :user_allowed
end
```
Now, if we want to perform another step in case the _user is not allowed_, we would end up with something like:

```elixir
defmodule Pipeline do
  use Opus.Pipeline

  step :do_this, if: :user_allowed
  step :do_another, if: :user_not_allowed
end
```

Which makes us implement two different functions (`user_not_allowed` and `user_allowed`) returning the opposite of the other. This would be simplified if we could do:

```elixir
defmodule Pipeline do
  use Opus.Pipeline

  step :do_this, if: :user_allowed
  step :do_another, unless: :user_allowed
end
```

**Comment by zorbash** [comment]
You could do:

```elixir
defmodule Pipeline do
  use Opus.Pipeline

  step :do_this, if: :user_allowed
  step :do_another, if: &(!__MODULE__.user_allowed(&1))
end
```

But I can totally see `unless` making the code more readable in your examples.
