### ISSUE TITLE
Disable importing instrumentation

### ISSUE THREAD

**Issue by churcho** [zorbash/opus#17]
I would like to use another module for handling instrumentation, the only issue is that it also implements `instrument/3` and that ambiguity creates a problem, how can I use Opus without that function being in the scope I am in?

**Comment by zorbash** [comment]
Out of curiosity what's the module (if open-source) that handles instrumentation in your case?

At the moment there is no option to skip the inclusion of the instrumentation macros. I'll try to think of a way to make that possible.

**Comment by churcho** [comment]
I am trying to use Appsignal. I found a way to get round that using the [decorators](https://docs.appsignal.com/elixir/instrumentation/instrumentation.html) it provides.

**Comment by churcho** [comment]
> I am trying to use Appsignal. I found a way to get round that using the [decorators](https://docs.appsignal.com/elixir/instrumentation/instrumentation.html) it provides.

If you find a way to make the two work with `instrument/3` without the ambiguous error flag do let me know as the `decorators` don't provide the low level logging I am looking for but it's available in `instrument/3`

**Comment by zorbash** [comment]
@churcho I'm already working on it. I'll close this issue for now.

**Comment by churcho** [comment]
@zorbash any luck? Really need to wire this.

**Comment by zorbash** [comment]
@churcho I thought it wasn't a blocking issue for you (https://github.com/zorbash/opus/issues/17#issuecomment-474694835).

**Comment by churcho** [comment]
Found the decorators limiting in the amount of data I can push through them. 
I will experiment with some other ways of getting around this, might have to call a context function from within the stage and it's that context function that lives outside of Opus that I will wire the instrumentation on. That looks like my safest bet.
