### ISSUE TITLE
question:  is there any equivalent  link+tee function ?

### ISSUE THREAD

**Issue by r8code** [zorbash/opus#23]
I want to pipe  to the other opus pipeline   but with behavior like tee , 
is there any function like that ,  or am I doing wrong ?
btw thx for this great library , it's like simplified saga pattern

**Comment by zorbash** [comment]
Hi @r8code !

So what I think you're trying to achieve is:

```elixir
defmodule CreateUserPipeline
  use Opus.Pipeline

  step :persist
  link UserNotificationPipeline
  step :respond
end
```

and in the code above, you don't want to halt the pipeline when `UserNotificationPipeline` completes with `{:error, _}`. Is this correct?

Well, at the moment the `link` stage is a `step` which accepts a pipeline module. You'd have to do something like:

```elixir
defmodule CreateUserPipeline
  use Opus.Pipeline

  step :persist
  tee :notify_user, with: &UserNotificationPipeline.call/1
  step :respond
end
```

or even write a more verbose function emulating this behaviour.
However, I see that configuring the behaviour or link can be very convenient.

**Comment by r8code** [comment]
Exactly what I want to achieve , 
Thx a lot
