### ISSUE TITLE
Bad instrumentation for skip stage

### ISSUE THREAD

**Issue by rafaels88** [zorbash/opus#4]
When trying to instrument the `skip` stage, we get a name that probably doesn't make too much sense (?). 

Also, when the pipeline is skipped (`skip` true), Opus treat it as an error.

### Environment

* opus version: `0.6.0`

### Current behavior

```elixir
defmodule Test do
    use Opus.Pipeline
    
    skip if: :skip?

    def skip?(_), do: true

    def instrument(:stage_completed, params, params2) do
        require Logger
        Logger.warn("#{inspect params} >>> #{inspect params2}")
    end
end
```

Output:

`%{stage: %{name: [if: :skip?], pipeline: Test}} >>> %{input: 1, result: {:error, :skipped}, stage: [if: :skip?], time: 31450000}`

### Expected behavior

1. Not sure what would be the expected behaviour in that case, since it's the only stage without a name?

2. `Skip` should not be an error

**Comment by zorbash** [comment]
This should be fixed now that 0.6.0 has been released and `skip/2` expects a name as the first argument.
