### ISSUE TITLE
Graphics used on Pipeline Execution wiki page

### ISSUE THREAD

**Issue by jpinnix** [zorbash/opus#6]
Hello,

What tool/template did you use to create the flowcharts on the Pipeline Execution wiki page? They look great.

Thanks,
Jeremy

**Comment by zorbash** [comment]
Hi @jpinnix, `Opus.Graph` is using [graphviz](https://www.graphviz.org/) under the hood.

Make sure to have it installed on your system

```shell
brew install graphviz
```

To try this with your pipelines:

```elixir
Opus.Graph.generate(:your_app, %{filetype: :svg})
```
